name: Concurrency-2
concurrency:
  group: ${{github.workflow}}-${{inputs.environment_input}}-concurrency
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      environment_input:
        type: environment
        required: true
        description: environment to deploy 2
jobs:
  sleep-and-deploy-to-some-environment:
    runs-on: ubuntu-latest
    steps:
      - name: delay 5 seconds
        run: sleep 5
      - name: deploying to environment
        run: echo "deploying to ${{inputs.environment_input}}"
