# DOCS: https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow
name: encrypt and decrypt secrets from a file
on: [push]
env:
  PASSPHRASE: ${{secrets.GPG_PASS_PHRASE}}
jobs:
  decrypt-file:
    runs-on: ${{vars.RUNNER_OS}}
    steps:
      - uses: actions/checkout/@v4
      - name: Decrypt large secret
        run: |
          echo "Runnnig decrypt script to decrypt secrets"
          chmod +x decrypt_script.sh
          ./decrypt_script.sh

      - name: view secrets-json content
        run: |
          echo "this is for test, dont print secrets in real projects"
          cat $HOME/secrets/secrets.json
