# use expressions, Context, if statement and functions in WF

name: expressions and Context
on: [push, issues, pull_request]
run-name: '${{github.actor}} runs ${{github.workflow}} on event: ${{github.event_name}} '
jobs:
  using-expressions-and-context:
    runs-on: ubuntu-latest
    # contains method is github fn the takes 2 arguments (array, value) and return boolean
    # formJson is a GH fn that convert an string to json
    if: contains(fromJson('["pull_request", "push"]'), github.event_name) || github.event_name == 'issues'
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo "'string' == 'String' ::>>" ${{'string' == 'String'}}
          echo "true || (false && true) ::>>"${{ true || (false && true) }}
          echo "1>2::>>" ${{1>2}}
      - name: print-Context-if-pull-request
        id: context
        if: github.event_name == 'pull_request'
        run: |
          echo '${{toJson(github)}}'
          echo 'Secrets: >> ${{toJson(secrets)}}}'
          echo 'Job: >> ${{toJson(job)}}}'
          echo 'Job.status: >> ${{toJson(job.status)}}}'
          echo 'runner info::>> ${{toJson(runner)}}'
      - name: print functions result -if push
        if: contains(fromJson('["push"]'), github.event_name)
        run: |
          echo 'this step will run if github.event_name is equal to push'
          echo 'contains result:>> ${{contains(fromJson('["pull_request", "push"]'), github.event_name)}}'

      #run if event_name is issues and had a label'bug'
      - name: run if it issue has a bug label
        if: contains(github.event.issue.labels.*.name, 'bug')
        run: |
          echo 'this will run if anissue is created with a label of bug'
          echo 'contains(github.event.issue.labels.*.name, 'bug')::>> ${{contains(github.event.issue.labels.*.name, 'bug')}}'
          echo ${{ join(github.event.issue.labels.*.name,  ' ,')}}
