# use expressions, Context and functions in WF

name: expressions and Context
on: [push, issues, pull_request]
run-name: '${{github.actor}} runs ${{github.workflow}} on event: ${{github.event_name}} '
jobs:
  using-expressions-and-context:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo "'string' == 'String' ::>>" ${{'string' == 'String'}}
          echo "true || (false && true) ::>>"${{ true || (false && true) }}
          echo "1>2::>>" ${{1>2}}
      - name: Context
        id: context
        if: github.event_name == 'pull_request'
        run: |
          echo '${{toJson(github)}}'
          echo 'Secrets: >> ${{toJson(secrets)}}}'
          echo 'Job: >> ${{toJson(job)}}}'
          echo 'Job.status: >> ${{toJson(job.status)}}}'
          echo 'runner info::>> ${{toJson(runner)}}'
