name: First work flow
on: [pull_request]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo This is a multi-line script
          echo The script is running on unbuntu
          node -v
          npm -v
  parrallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View the path
        run: echo $PATH
      - name: View SW version
        run: sw_vers
  depenedent-job_windows:
    runs-on: windows-latest
    needs: [run-shell-commands]

    steps:
      - name: run depenedent job on windows
        run: Write-Host "Hello, world!"
  dependent_job_mac:
    runs-on: macos-latest
    needs: parrallel-job-macos
    steps:
      - name: get System information
        run: system_profiler SPSoftwareDataType SPHardwareDataType
