# to manually run a workflow manual only, we use the event workflow_dispatch
name: deploy to stage env
on:
  workflow_dispatch:
    inputs:
      Developer_name:
        type: string
        description: Name of the developer runnig the WF.
jobs:
  run-a-manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: deploying to stage env
        run: |
          echo deploynig to stg environment
