# trigger a WF by calling the GH REST API and send the matrix in the payload

name: manul-trigger-matrix
on:
  workflow_dispatch:
    inputs:
      os:
        type: string
        required: true
        default: 'ubuntu-latest,macos-latest,windows-latest'
        description: os to run the job
      node-version:
        type: string
        required: true
        default: '18,20'

jobs:
  run-dynamic-matrix-manually:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
        node-version: ${{fromJson(inputs.node-version)}}
    steps:
      - name: print node version
        run: node -v

      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: print node version after matrix
        run: node -v
      - name: print inputs
        run: echo "inputs :::>>>" ${{toJson(inputs.node-version)}}
