# to manually run a workflow manual only, we use the event workflow_dispatch
name: manual-deploy
on:
  workflow_dispatch:
    inputs:
      Developer_name:
        type: string
        required: true
        default: Romany Sefen
        description: Name of the developer runnig the WF.
      Years:
        type: number
        required: true
        default: 45
        description: How many years you have been in the company?
      your_Gender:
        type: choice
        required: true
        default: 'Male'
        options:
          - Male
          - Female
          - Not to Say
jobs:
  run-a-manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: deploying to stage env
        run: |
          echo "Developer name running this workflow is: ${{inputs.Developer_name}}"
          echo "::warning title="years in the company":: You have been for ${{inputs.Years}} years in the company."
          echo "Your gender is ${{inputs.your_Gender}}"

    # we can trigger the event by calling the GH Reast API
    # https://api.github.com/repos/Romany-GL/yaml-to-json/actions/workflows/manual-wf.yaml/dispatches
    # payload:

#     {
#   "ref": "main",
#   "inputs": {
#     "Developer_name": "Postman",
#     "Years": "5",
#     "your_Gender": "Male"
#   }
# }
