# event repoistory_dispatch to trigger WF by GH Restful API
# types: must match the event_type sent in the post request
# token used in the API call must have content write access
# this workflow will dynamically create matrix by calling the GH REST API (on: repository_dispatch)

name: matrix-dynamic-by-call-api
on:
  repository_dispatch:
    types:
      - triger-matrix-by-api
jobs:
  create-matrix-from-payload:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ${{github.event.client_payload.os}}
        node_version: ${{ github.event.client_payload.node_version}}
        include:
          - os: macos-latest
            is-mac: true
          - os: ubuntu-latest
            is-ubuntu: true
          - os: windows-latest
            node_version: 16
            is-windows: true
    steps:
      - name: print-node-version-before-matrix
        run: node -v

      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node_version}}

      - name: print-node-version-after-matrix
        run: node -v

      - name: print system info if mac
        if: ${{matrix.is-mac}}
        run: System_profiler SPSoftwareDataType SPHardwareDataType

      - name: print system info if windows
        if: ${{matrix.is-windows}}
        run: |
          whoami
          systeminfo

#  event_type sent in the post request must match types key defined in the WF to trigger the WF
#  token used in the API call must have content write access
# https://api.github.com/repos/Romany-GL/yaml-to-json/dispatches
# payload:
#     {
#         "event_type": "triger-matrix-by-api",
#         "client_payload": {
#           "os": ["ubuntu-latest","macos-latest"],
#           "node_version" : ["18","20"]
#         }
#       }
