name: pull and checkout repository
on: [pull_request]
jobs:
  pull-repo-and-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: list files before pull
        run: ls -a
      - name: checkout
        run: |
          git init
          git branch -m main
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: list files after checkout
        run: ls -a
