# to create reusable Wf we use the event workflow_call, we can define inputs ,outputs and secrets in this event

name: reusable-workflow
on: 
    workflow_call:
        inputs: 
            name:
                type: string
                required: true
        secrets:
            custom-token:
                description: this is the secret defined in the repo setting
                required: true
                
        outputs:
            user-object: 
                description: this is the person defined in the job below
                value: ${{jobs.generate-outputs.outputs.person}} 
         
jobs:
    generate-outputs:
        runs-on: ubuntu-latest
        outputs:
            person: ${{steps.step-1.outputs.result}}
        steps:
            - uses: actions/github-script@v7
              id: step-1
              with:
                script: |
                 const person = { fname: 'romany' , lname: 'Sefen'}
                 return person

            - name: print greeting
              run: echo 'Welcome:::>> ${{toJson(steps.step-1.outputs) }} '