# run a wf on a scheduled time, in this WF we mark issu as stale after a certain time
name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '01 15 * * *' #https://crontab.guru/
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issues-message: 'this issue is stale because it has been open more the 3 days with no activity'
          days-before-issue-stale: 3
          days-before-pr-stale: 1
          days-before-close: 1
          days-before-issue-close: 2
          days-before-pr-close: 3
          stale-issue-label: 'no-activity'
