# pull_request_target is similar to pull_request but it uses the wf code from the main branch not the mofified, to prevent malecious code ran from forked branches
name: use-pull-request-target
on:
  pull_request_target:
    types: [opened, closed, reopened, synchronize, assigned, unassigned]

jobs:
  add-a-comment-to-PR:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '👋 Thanks for reporting!'
            })
