name: use reusable wf from another repo
on: 
    workflow_dispatch:
     inputs:
        name: 
            type: string
            required: true
            default: Romany
            description: Write your name 
 # this job uses the reusable WF from the reusable-wf-repo @main branch, it doesn't have a runs-on key or steps because they are defined on the reusable WF
 # The `uses` key will be defined on the job level not on the step level as we do in actions  
jobs:
   call-reusable-wf:
        uses: Romany-GL/reusable-wf-repo/.github/workflows/reusable.yaml@main
        with:
            name: ${{inputs.name}}
        secrets:
            custom-token: ${{secrets.CUSTOM_TOKEN}}
   log-inputs-in-repo:
     runs-on: ubuntu-latest
     steps:
       - name: log inputs from the wf
         run: echo 'Inputs from repo:>' ${{inputs.name}}

       - name: log secretes in repo
         run: echo "${{secrets.CUSTOM_TOKEN}}"

   log-outputs-from-reusable-repo:
      runs-on: ubuntu-latest
      needs: call-reusable-wf
      steps:
        - name: print-outputs-from-reusable-wf-in-other-repo
          run: |
            echo "welcome " ${{needs.call-reusable-wf.outputs.firstName}}

           