name: use-composite-action
on:
  workflow_dispatch:
    inputs:
      your-name:
        type: string
        default: romany sefen
        required: true
jobs:
  use-of-composite-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/composite-action
        id: use-custom-composite-action
        with:
          who-to-greet: ${{inputs.your-name}}
      - name: print random number from custom action
        shell: bash
        run: echo "out put ${{steps.use-custom-composite-action.outputs.random-number }}"
