name: use custom action created by template
env:
  my-token: ${{secrets.GITHUB_TOKEN}}
on:
  workflow_dispatch:
    inputs:
      milliseconds:
        type: number
        required: true
        default: 1000
        description: 'Milliseconds bdfore run the action'
      title:
        type: string
        required: true
        description: 'Title of the Issue'
      body:
        type: string
        required: true
        description: 'body of the Issue'
      assignees:
        type: string
        description: 'Issue assignees'
      token:
        type: string
        required: true
        default: '123'

jobs:
  use-action:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: RomanyU1662160/action-with-js-template@v1.3
        id: action-step
        with:
          title: ${{inputs.title}}
          body: ${{inputs.body}}
          milliseconds: ${{inputs.milliseconds}}
          assignees: ${{inputs.assignees}}
          token: ${{secrets.GITHUB_TOKEN}}

      - name: print outputs from action
        run: |
          echo "Greeting message from action output::::>>>> ${{steps.action-step.outputs.GreetingMsg}}"
          echo "Time from action output:::::>>>> ${{steps.action-step.outputs.time}}"
