# access rep, environments  and orgnization varibales and secrets
name: secrets and environments
on: [push]
jobs:
  access-environment-vars:
    runs-on: ${{vars.RUNNER_OS }}
    environment: 'staging'
    env:
      REPO_BOOLEAN_SECRET: ${{secrets.REPO_LEVEL_SECRET_BOOLEAN}}
      STG_BOOLEAN_SECRET: ${{secrets.STG_SECRET}}
    steps:
      - name: log-repo-variables-if-boolean-secret-is-true
        if: ${{env.STG_BOOLEAN_SECRET}}== 'true'
        run: |
          echo "STG variable ${{vars.RUNNER_OS}}"
          echo "env- STG Secret ${{env.STG_BOOLEAN_SECRET}}"
          echo "env- REPO Boolean Secret ${{env.REPO_BOOLEAN_SECRET}}"
          echo "secrets- STG Secret ${{secrets.STG_SECRET}}"
          echo "STG variable- STG Secret ${{vars.STG_VAR}}"
          echo "secrets- REPO Boolean Secret ${{secrets.REPO_LEVEL_SECRET_BOOLEAN}}"
          echo "env_Repo_level_secret: $REPO_BOOLEAN_SECRET"
          echo "env_Repo_level_var: ${{vars.REPO_LEVEL_VAR}}"
          echo "env_Repo_level_RUNNER_VAR: $RUNNER_OS"
