# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
name: run-workflow-based-on-another-workflow
on:
  workflow_run:
    workflows: [use-pull-request-target, GH-Events-Exapmle]
    types: [completed]
jobs:
  run-after-gh-events-completed:
    runs-on: ubuntu-latest
    steps:
      - name: log-success-message
        uses: actions/github-script@v7
        with:
          script: |
            console.log("this WF runs after the GH EVENT EXAMPLE WF is completed")

      - name: run-on-success
        if: ${{ github.event.workflow_run.conclusion == 'success'}}
        run: echo 'The triggering workflow passed'
      - name: run on failure
        if: ${{github.event.workflow_run.conclusion =='failure' }}
        run: echo 'The triggering workflow failed'
